### ISSUE TITLE
Create POST route that will store data in db

### ISSUE THREAD

**Issue by jwlehman93** [Purdue-ACM-SIGAPP/PurdueLaundry-StatCollectorApi#3]
Create a route that StatCollector service can hit to send machine stats to database.

**Comment by vidia** [comment]
@jwlehman93 Are you still doing this? The Python you have makes a DB cursor so I'm not sure if you are planning to write to the DB directly there or not.

**Comment by jwlehman93** [comment]
Yes, that was when I was thinking of interfacing directly with DB. Now, it will be routed through the api, so it still needs to be done, just not via the db. There is honestly no longer a need for the db connection so that can be removed in order to complete this. @vidia
